---
title: "`r params$title`"
output: html_document
params:
  title: "Full Results"
  results_dir: "~/storage/Atlas_lab_app/test_output"
  #default "DMSO" MAKE SURE THE CONTROL IS RIGHT OR ELSE IT WILL BREAK DUE TO STATS COMPARISONS 
  control_name: "DMSO" 
  control_dose: NA
---
```{r}
# Access the parameters
results_dir <- params$results_dir
control_name <- params$control_name
control_dose <- params$control_dose

```

```{r run script, echo = FALSE, warning = FALSE, message = FALSE, progress = FALSE} 
source("Replicate analysis.R", local = TRUE)

```

```{r plotly-crosstalk, eval = TRUE, echo = FALSE,warning = FALSE, message = FALSE, progress = FALSE, include = TRUE}
library(DT)
library(dplyr)
library(tidyr)
library(tm)
library(ggplot2)
library(forcats)
library(plotrix)
library(matrixStats)
library(remotes)
library("multcompView")
library("plotly")
library("crosstalk")
library("d3scatter")


chemical_ct <- SharedData$new(df3)

dt <- datatable(chemical_ct)
dt
filter_checkbox("chl", "chemical", chemical_ct, ~chemicalgroup, inline = TRUE)

# Specify a set of main colors
main_colors <- c("red", "blue", "green", "yellow", "orange", "purple", "cyan", "magenta", "brown", "gray")
print("Signif. codes: ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘o’ 0.1")
# Create the plot with dynamically adjusted bar width
plot <-plot_ly(
  data = chemical_ct,
  x = ~graphing_sort,
  y = ~Metric,
  type = input$plot_type,
  boxpoints = "all",
  jitter = 0.3,
  name = ~chemicalgroup, 
  quartilemethod="linear",
  color = ~graphing_sort,
  colors = main_colors,
  #
  texttemplate = ~sigcode,
  textposition = "outside",
  textfont = list(color = "black",
                  size = 30),
  outsidetextfont = list(color="black"),
  #
  error_y = list(
    type = 'data', 
    array = ~SEM,
    color = "black"
  )
) %>%
  layout(
    xaxis = list(title = "Chemical",
                 tickmode = 'array',  # Set tick mode to 'array'
                  tickvals =  df3$graphing_sort, # Set tick values to be the same as x 
                    ticktext = df3$graphing_sort,
                 tickangle = 90 ),
    yaxis = list(
      title = names(analysis_choices)[which(analysis_choices == input$data_analysis_type)],
      fixedrange = TRUE,
      range(0, NA),
      rangemode = 'tozero'
    ),
    bargap = 0.1,
    width = 800, 
    height = 800
  ) 
plot


```

